// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagerWebAPI.Models;

public partial class Project
{
    public int ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string ProjectDescription { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}