// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagerWebAPI.Models;

public partial class Task
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime DueDate { get; set; }

    public int ProjectId { get; set; }

    public int? ParentId { get; set; }

    public byte[] AttachmentData { get; set; }

    public string AttachmentName { get; set; }

    public string AttachmentType { get; set; }

    public virtual ICollection<Task> SubTasks { get; set; } = new List<Task>();

    public virtual Task Parent { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<TaskUser> TaskUsers { get; set; } = new List<TaskUser>();
}