// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagerWebAPI.Models;

public partial class TaskUser
{
    public int TasksId { get; set; }

    public string UsersId { get; set; }

    public virtual Task Tasks { get; set; }

    public virtual User Users { get; set; }
}